### ISSUE TITLE
Instagram scape no longer working on Android

### ISSUE THREAD

**Issue by eduardo-mior** [shalanah/inapp-debugger#11]
A few days ago I noticed an update on Android that caused the tricks to force open Google Chrome to stop working on Android.

Is this correct? Has anyone else noticed this?

**Comment by shalanah** [comment]
Hi @eduardo-mior 
Can you send me a screenshot or copy paste the UA info when you're in Instagram?
Definitely will look into!

**Comment by shalanah** [comment]
I'm experiencing issues in Instagram, Facebook App, Threads, and Messenger but it works in Telegram.

Android 14
Chrome 130.0.6723.58

(regular Chrome is at 13.0.0.0)

**Comment by shalanah** [comment]
These in-app browsers are such nightmares! 
I'm unsure of another way at the moment to get around this. Not sure if other app schemas (Chrome etc) may work just yet.

**Comment by eduardo-mior** [comment]
> Hi @eduardo-mior Can you send me a screenshot or copy paste the UA info when you're in Instagram? Definitely will look into!

Android 11
Xiaomi Mi A3
Instagram version 355.0.0.37.103
  
User Agent:
Mozilla/5.0 (Linux; Android 11; Mi A3 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.14 Mobile Safari/537.36 Instagram 355.0.0.37.103 Android (30/11; 320dpi; 720x1411; Xiaomi; Mi A3; laurel_sprout; qcom; pt_BR; 657300861)

Device: Mobile
Vendor: N/A
OS: Android
Version Name: N/A
Version: 11
Browser: Chrome
Browser Version: 131.0.6778.14
Engine: Blink

**Comment by eduardo-mior** [comment]
> These in-app browsers are such nightmares! I'm unsure of another way at the moment to get around this beside specific directions UI. Not sure if other app schemas (Chrome etc) may work just yet.

Apparently it's a new update from Facebook, Instagram, etc.

This update has become a nightmare in Brazil. No application can be opened directly anymore, not even WhatsApp or Facebook, which are from Meta.

Many, many people put their WhatsApp link in their Instagram bio. With this, visitors to the page could open WhatsApp directly with the person by just clicking on the link. With this new update, WhatsApp is no longer opening automatically.

This way, people need to manually type in the WhatsApp number and this has many drawbacks!

**Comment by shalanah** [comment]
Wow! I'm hoping they fix with an app update. I didn't know about the WhatsApp number! This is pretty awful. 

And to think, I checked the escape/intent links out just last week!

I'll probably add more Android UAs to make sure I catch these case appropriately. 

I've tried to avoid app version detection since that gets out of hand fast, but may be something worth looking into if Meta doesn't fix and recognize this as an error.

**Comment by eduardo-mior** [comment]
@shalanah If I remember correctly, there are 3 or 4 methods to force the in-app browser to open Google Chrome or the default browser on your phone. But from what I've seen, all of these hacks stopped working together. It seems that Meta did something on purpose to prevent everything.

There is a trick where you put an <a> link on the screen that downloads a fake PDF, this forced Instagram to open the browser, but this trick stopped working.

There is another trick that involves changing the location.href to something like intent://{{link}} or `googlechrome://${link}` but it also stopped working.

**Comment by shalanah** [comment]
Here's what I have for Android Meta Apps intent links:
- Facebook/Messanger - v481 (and maybe earlier) intent link no longer works
- Instagram/Threads - v355 (and maybe earlier) intent link no longer works

**Comment by shalanah** [comment]
Maybe it was a bug - but now Facebook and Instagram intent links seem to work for me but Messenger and Threads don't.

**Comment by shalanah** [comment]
For me only Threads doesn't work now. Instagram, FB, Messenger all work with intent links now.

**Comment by shalanah** [comment]
Looks like this was a Meta bug. All intent links have been fixed in the latest builds.
