### ISSUE TITLE
How to force open in-app instagram link to default browser?

### ISSUE THREAD

**Issue by neestzjov** [shalanah/inapp-debugger#6]
How to force open in-app instagram link to default browser?

**Comment by shalanah** [comment]
Hi @neestzjov! Great question. 

[InAppDebugger](https://inappdebugger.com) has a couple of escape methods [InAppDebugger Github](https://github.com/shalanah/inapp-debugger) and here's a break down of solutions: [Stackoverflow](https://stackoverflow.com/questions/76888215/open-link-in-system-browser-instead-of-in-app-browser/77466893#77466893)

It will be different for Android vs Apple devices. 
I use [bowser](https://www.npmjs.com/package/bowser/v/1.9.4 to help detect OS and device type.

Hope that helps!

**Comment by neestzjov** [comment]
> Hi @neestzjov! Great question.
> 
> [Solutions on Stackoverflow](https://stackoverflow.com/questions/76888215/open-link-in-system-browser-instead-of-in-app-browser/77466893#77466893) has a great breakdown.
> 
> You can also use [InAppDebugger](https://inappdebugger.com) to test and try of escape methods [InAppDebugger Github](https://github.com/shalanah/inapp-debugger).
> 
> Escape methods are different for Android vs Apple devices. I use [bowser](https://github.com/bowser-js/bowser) to help detect OS and device type.
> 
> Hope that helps!

I am interested first to solve it for iOS devices. Yes it works with x-safari-https but it only opens Safari not user's default browser. User default browser could be chrome so we don't know his preferences. I want the link opened as user's preference which could be chrome, safari, opera etc

**Comment by neestzjov** [comment]
> > Hi @neestzjov! Great question.
> > [Solutions on Stackoverflow](https://stackoverflow.com/questions/76888215/open-link-in-system-browser-instead-of-in-app-browser/77466893#77466893) has a great breakdown.
> > You can also use [InAppDebugger](https://inappdebugger.com) to test and try of escape methods [InAppDebugger Github](https://github.com/shalanah/inapp-debugger).
> > Escape methods are different for Android vs Apple devices. I use [bowser](https://github.com/bowser-js/bowser) to help detect OS and device type.
> > Hope that helps!
> 
> I am interested first to solve it for iOS devices. Yes it works with x-safari-https but it only opens Safari not user's default browser. User default browser could be chrome so we don't know his preferences. I want the link opened as user's preference which could be chrome, safari, opera etc

Also shortcuts method is a bit strange as it redirects to shortcuts then again to browser. If you don't have shortcuts installed it opens appstore and so on.

**Comment by shalanah** [comment]
@neestzjov  The only two methods that seem super reliable on iOS are the Safari + shortcuts. If you find another method let me know! I do think Apple has a big blindspot here that they should fix.

You could surface the option the the user as buttons to open in Safari or Chrome etc with those links so the user could decide.
