### ISSUE TITLE
Shortcuts fallback no longer working in iOS 18.1 beta

### ISSUE THREAD

**Issue by shalanah** [shalanah/inapp-debugger#8]
All good things must come to an end, even our trusty escape links with Apple.

We knew it was only a matter of time before Apple would close the loophole we used for opening links in the default browser.

Dear Apple 🙏—can we please have a solution to bypass in-app browsers, like Android's intent links on iOS?

Can anyone else confirm if this workaround is no longer functional? I'm on 18.1 beta and wondering if the fix is already in place in 18.1.

**Comment by shalanah** [comment]
Tagging @Pinjasaur for notificiation

**Comment by Pinjasaur** [comment]
Oof. I don't have an iOS device to test. Perhaps @hisaac?

**Comment by hisaac** [comment]
I haven't updated to 18.1 yet — still on 18.0.1 until 18.1 is officially released. I'm too old to install betas these days 😅.

I'm happy to test at that point if you need.

**Comment by Pinjasaur** [comment]
I'm _potentially_ willing to chalk it up to a beta bug. Their iOS 18 docs for it are still good: https://support.apple.com/guide/shortcuts/use-x-callback-url-apdcd7f20a6f/ios.

Guess we'll have to wait and see. 🤞🏻

**Comment by shalanah** [comment]
I have 18.1 running here's the screenshot. :( 
Looks like Safari link is the most reliable. Wish we had something to our default browser on iOS. It's a shame.

![image_123655411](https://github.com/user-attachments/assets/59fc6659-3192-453d-9175-906596f959e3)

**Comment by shalanah** [comment]
@hisaac Can you confirm that the shortcuts workaround doesn't work in 18.1?

**Comment by Pinjasaur** [comment]
@hisaac pinged on this out of band on how to test, so just wanted to write that down here quick for posterity even though we're working from a coffee shop together right now.

The gist is you need to load up <https://inappdebugger.com/> in an in-app browser. There's a list in the [README](https://github.com/shalanah/inapp-debugger#ios) but _most_ social media apps should do the trick. Last time I asked you for help we used Instagram either by sending it in a DM or attaching the URL to a profile, etc.

Once you load that, scroll down to the iOS escape hatch links and try the "shortcuts fallback":

<img width="499" alt="image" src="https://github.com/user-attachments/assets/5980c256-902c-472d-9bcc-65d3459d8dc3">

**Comment by shalanah** [comment]
It's good to know it's happening. 
I'll update inappdebugger website with some text to say it worked from at least v17 (maybe even before!) through 18.0.

**Comment by ericpoulinnz** [comment]
Has there been any updates from Apple / anyone on this? I see 18.1.1 was released and 18.2 is in beta. Really hoping to find a way around this 😩
