### ISSUE TITLE
Fix Android intent link format

### ISSUE THREAD

**Issue by shalanah** [shalanah/inapp-debugger#9]
See https://github.com/shalanah/inapp-spy/issues/30

Seems like our published format works really well but not in all in-app browsers like Telegram.

**Comment by shalanah** [comment]
Change 
`intent:https://example.com#Intent;end`

To 
`intent://example.com#Intent;scheme=https;end`

**Comment by shalanah** [comment]
Tagging @Pinjasaur for notification

**Comment by Pinjasaur** [comment]
Nice find. Got any docs on this?

**Comment by shalanah** [comment]
Not any off hand but can take a gander!

**Comment by shalanah** [comment]
I can't seem to find it right now :( but if I come across it I will post here.
This is an explanation of android intents but with a scheme of another app not a scheme of https/http
https://developer.chrome.com/docs/android/intents 

There is a lot of documentation around creating these links in Android apps but not building them with strings to use as urls.

**Comment by shalanah** [comment]
Here's a mention of this technique:
https://stackoverflow.com/a/77665038/2824643

**Comment by zehawki** [comment]
> Nice find. Got any docs on this?
> There is a lot of documentation around creating these links in Android apps but not building them with strings to use as urls.

Here's a really old resource that talks about this https://marcelbraghetto.github.io/android/2015/09/04/intent-links/, and links to a page thats 404 now (https://developer.chrome.com/multidevice/android/intents). Given that this info is simply no longer available / documented anywhere official, me thinks its a left over from earlier and one of these days our overlords will remove this.
